'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

type NavItem = { label: string; href: string };
type StatItem = { value: string; label: string };
type FeatureItem = { n: string; icon: string; bg: string; title: string; desc: string };
type ModuleItem = { badge: string; title: string; href: string; desc: string };
type InsightItem = { chip: string; chipClass: string; title: string; desc: string };

// ── STEP 1 FIX: Added Dietitians to NAV ──────────────────
const NAV_ITEMS: NavItem[] = [
  { label: 'Trainers',      href: '/trainers' },
  { label: 'Nutritionists', href: '/nutritionists' },
  { label: 'Dietitians',    href: '/dietitians' },
  { label: 'Gym Packages',  href: '/gym-packages' },
  { label: 'Meal Plans',    href: '/meals' },
  { label: 'Supplements',   href: '/supplements' },
  { label: 'Articles',      href: '/articles' },
];

const HERO_STATS: StatItem[] = [
  { value: '47K+',  label: 'Active Members'   },
  { value: '1,200+',label: 'Certified Experts' },
  { value: '98.4%', label: 'Goal Completion'  },
  { value: '4.9 / 5',label: 'User Rating'     },
];

const FEATURE_CARDS: FeatureItem[] = [
  { n:'01', icon:'⚡', bg:'rgba(198,241,53,0.07)',  title:'AI Workout Engine',           desc:'Adaptive workout plans generated from your goals, body metrics, training level, recovery trends, and weekly consistency — updated as you improve.' },
  { n:'02', icon:'🥗', bg:'rgba(0,212,255,0.07)',   title:'Smart Nutrition Intelligence',desc:'Daily macro targeting, AI meal generation, calorie structuring, and personalized food planning. Download expert-built PDF plans instantly.' },
  { n:'03', icon:'👥', bg:'rgba(139,92,246,0.07)',  title:'Expert Booking Ecosystem',    desc:'Book certified trainers, nutritionists, and registered dietitians through polished profiles, direct messaging, and guided session flows.' },
  { n:'04', icon:'📍', bg:'rgba(244,63,94,0.07)',   title:'Discover Nearby Gyms',        desc:'Premium gym discovery with location-aware listings, package pricing, enrollment flow, and verified gym packages.' },
  { n:'05', icon:'📈', bg:'rgba(245,158,11,0.07)',  title:'Progress Analytics',          desc:'Track workouts, body metrics, calorie logs, water intake, streaks, and long-term improvement through real-time dashboards.' },
  { n:'06', icon:'🧬', bg:'rgba(198,241,53,0.07)',  title:'Predictive Health Guidance',  desc:'AI-powered weekly summaries, smart habit insights, BMI/TDEE calculator, and leaderboard streaks to keep you consistent.' },
];

const MODULE_CARDS: ModuleItem[] = [
  { badge:'Core',        title:'AI Workouts',    href:'/workouts/generate', desc:'Dynamic routines tailored to your goals, experience level, split preference, and training intensity — generated by GPT-4o.' },
  { badge:'Nutrition',   title:'Meal Plans',     href:'/meals',             desc:'Download professional PDF meal plans or generate a custom AI plan. 8 plans available: keto, vegan, diabetic, cardiac, and more.' },
  { badge:'Performance', title:'Supplements',    href:'/supplements',       desc:'Smart supplement discovery with goal-based recommendations, product details, and a full cart and checkout system.' },
  { badge:'Consulting',  title:'Bookings',       href:'/bookings',          desc:'Book trainer sessions, nutrition consultations, and dietitian appointments. Manage, reschedule, and track all sessions.' },
  { badge:'Analytics',   title:'Progress',       href:'/progress',          desc:'Log daily calories, water, weight, and workouts. View streaks, trends, charts, and milestone achievements.' },
  { badge:'Learning',    title:'Articles',       href:'/articles',          desc:'Expert health and fitness articles, workout guides, nutrition education, and supplement research in one content hub.' },
];

const INSIGHT_CARDS: InsightItem[] = [
  {
    chip: 'Nutrition', chipClass: 'chip-cyan',
    title: 'AI Meal Generation',
    desc: 'Generate a personalized meal plan in seconds using GPT-4o. Set your goal, diet type, activity level, allergies, and calories — the AI does the rest.',
  },
  {
    chip: 'Specialists', chipClass: 'chip-violet',
    title: 'Dietitians & Nutritionists',
    desc: 'Access both Registered Dietitians (clinical, medical conditions) and certified Nutritionists (wellness, performance) — two separate expert networks.',
  },
];

const JOURNEY_STEPS = [
  { n:'01', title:'Discover the platform',       desc:'Trainers, nutritionists, dietitians, gym packages, meal plans, supplements, and AI tools — all in one premium platform.' },
  { n:'02', title:'Build your personalized path', desc:'After signup, the AI generates your workout and meal plan. Book a trainer or dietitian in under 60 seconds.' },
  { n:'03', title:'Improve through consistency',  desc:'Track habits, goals, coaching, nutrition, and progress. The dashboard gets smarter the more you use it.' },
];

const TRUST_ROW = [
  'AI Workout Plans','Smart Nutrition','Expert Trainers','Registered Dietitians',
  'Progress Analytics','Nearby Gyms','Meal Planning','Supplements','Health Education','Bookings','Body Tracking','Leaderboard',
];

const ACCENT_CLASSES = ['accent-1','accent-2','accent-3','accent-4','accent-5','accent-6'] as const;

export default function Home() {
  const [mousePos,  setMousePos]  = useState({ x: 0, y: 0 });
  const [isLoggedIn,setIsLoggedIn]= useState(false);
  const [mounted,   setMounted]   = useState(false);

  useEffect(() => {
    const syncAuth = () => {
      if (typeof window === 'undefined') return;
      setIsLoggedIn(!!localStorage.getItem('token'));
    };
    setMounted(true);
    syncAuth();
    const onMouse    = (e: MouseEvent) => setMousePos({ x: e.clientX, y: e.clientY });
    const onStorage  = () => syncAuth();
    const onAuth     = () => syncAuth();
    window.addEventListener('mousemove', onMouse);
    window.addEventListener('storage', onStorage);
    window.addEventListener('urbanwell-auth-changed', onAuth);
    return () => {
      window.removeEventListener('mousemove', onMouse);
      window.removeEventListener('storage', onStorage);
      window.removeEventListener('urbanwell-auth-changed', onAuth);
    };
  }, []);

  const brandHref = useMemo(() => {
    if (!mounted) return '/';
    return isLoggedIn ? '/dashboard' : '/';
  }, [mounted, isLoggedIn]);

  const handleLogout = () => {
    if (typeof window === 'undefined') return;
    localStorage.removeItem('token');
    window.dispatchEvent(new Event('urbanwell-auth-changed'));
    window.location.href = '/';
  };

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800;900&display=swap');

        *, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }

        :root {
          --void:#03050a; --deep:#060b12; --panel:#0a1220; --panel2:#0f1a2e;
          --lime:#c6f135; --cyan:#00d4ff; --violet:#8b5cf6;
          --rose:#f43f5e; --amber:#f59e0b;
          --text:#e2ecff; --sub:#4d6b8a; --line:rgba(0,212,255,0.08);
          --font-display:'Plus Jakarta Sans',sans-serif;
          --font-body:'Plus Jakarta Sans',sans-serif;
          --font-mono:'JetBrains Mono',monospace;
        }

        html { scroll-behavior: smooth; }
        body { background:var(--void); color:var(--text); font-family:var(--font-body); overflow-x:hidden; -webkit-font-smoothing:antialiased; }

        body::before {
          content:''; position:fixed; inset:0;
          background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.03'/%3E%3C/svg%3E");
          pointer-events:none; z-index:9999; opacity:0.38;
        }

        .page {
          min-height:100vh; position:relative;
          background:
            radial-gradient(circle at top left,rgba(0,212,255,0.05),transparent 30%),
            radial-gradient(circle at 85% 12%,rgba(198,241,53,0.05),transparent 22%),
            linear-gradient(180deg,#03050a 0%,#07101d 100%);
        }

        .aurora {
          position:fixed; width:720px; height:720px; border-radius:50%;
          pointer-events:none; z-index:0; transform:translate(-50%,-50%);
          transition:left 0.08s ease,top 0.08s ease;
          background:radial-gradient(circle at center,rgba(0,212,255,0.035) 0%,rgba(139,92,246,0.02) 40%,transparent 70%);
        }

        /* ── NAV ── */
        .nav {
          position:sticky; top:0; left:0; right:0; z-index:1000;
          height:76px; display:flex; align-items:center; justify-content:center;
          backdrop-filter:blur(24px) saturate(180%);
          background:rgba(3,5,10,0.74);
          border-bottom:1px solid var(--line);
        }
        .nav-inner {
          width:min(1320px,calc(100% - 32px));
          display:flex; align-items:center; justify-content:space-between; gap:18px;
        }
        .logo-mark { display:flex; align-items:center; gap:10px; text-decoration:none; flex-shrink:0; }
        .logo-icon {
          width:36px; height:36px;
          background:linear-gradient(135deg,var(--lime),var(--cyan));
          border-radius:10px; display:flex; align-items:center; justify-content:center;
          font-size:16px; font-weight:900; color:#000; font-family:var(--font-display);
          box-shadow:0 14px 28px rgba(198,241,53,0.14);
        }
        .logo-text { font-family:var(--font-display); font-size:20px; font-weight:800; letter-spacing:-0.6px; color:var(--text); }
        .logo-text em { font-style:normal; color:var(--lime); }

        .nav-center {
          display:flex; gap:4px;
          background:rgba(255,255,255,0.03); border:1px solid var(--line);
          border-radius:999px; padding:4px;
          overflow-x:auto; scrollbar-width:none; max-width:820px;
        }
        .nav-center::-webkit-scrollbar { display:none; }
        .nav-pill {
          padding:9px 15px; border-radius:999px;
          font-size:13px; font-weight:700; color:var(--sub);
          text-decoration:none; transition:all 0.22s ease;
          letter-spacing:0.1px; white-space:nowrap;
        }
        .nav-pill:hover { color:var(--text); background:rgba(255,255,255,0.06); }
        .nav-pill.dietitian { color:var(--cyan); }
        .nav-pill.dietitian:hover { background:rgba(0,212,255,0.08); }

        .nav-right { display:flex; gap:10px; align-items:center; flex-shrink:0; }

        .btn-nav-ghost,.btn-nav-cta,.btn-nav-danger {
          height:44px; padding:0 18px;
          font-size:13px; font-weight:700; border-radius:12px;
          text-decoration:none; transition:all 0.25s;
          display:inline-flex; align-items:center; justify-content:center;
          cursor:pointer; font-family:var(--font-display); letter-spacing:-0.1px; border:none;
        }
        .btn-nav-ghost { color:var(--text); background:rgba(255,255,255,0.02); border:1px solid var(--line); }
        .btn-nav-ghost:hover { border-color:rgba(0,212,255,0.18); background:rgba(255,255,255,0.05); }
        .btn-nav-cta { color:#000; background:var(--lime); box-shadow:0 0 24px rgba(198,241,53,0.24); }
        .btn-nav-cta:hover { background:#d7ff4e; transform:translateY(-1px); }
        .btn-nav-danger { color:#000; background:var(--rose); box-shadow:0 0 20px rgba(244,63,94,0.22); }
        .btn-nav-danger:hover { background:#f76479; transform:translateY(-1px); }

        /* ── HERO ── */
        .hero {
          min-height:calc(100vh - 76px);
          display:flex; flex-direction:column; align-items:center; justify-content:center;
          text-align:center; padding:120px 24px 92px;
          position:relative; z-index:1; overflow:hidden;
        }
        .hero-mesh {
          position:absolute; inset:0; pointer-events:none;
          background:
            radial-gradient(ellipse 80% 50% at 20% 60%,rgba(0,212,255,0.04) 0%,transparent 60%),
            radial-gradient(ellipse 60% 40% at 80% 40%,rgba(139,92,246,0.05) 0%,transparent 60%),
            radial-gradient(ellipse 40% 60% at 50% 90%,rgba(198,241,53,0.03) 0%,transparent 60%);
        }
        .hero-dots {
          position:absolute; inset:0; pointer-events:none;
          background-image:radial-gradient(circle,rgba(0,212,255,0.12) 1px,transparent 1px);
          background-size:40px 40px;
          mask-image:radial-gradient(ellipse 80% 80% at 50% 50%,black 20%,transparent 80%);
        }
        .hero-ring {
          position:absolute; width:620px; height:620px; border-radius:50%;
          border:1px solid rgba(0,212,255,0.05);
          top:50%; left:50%; transform:translate(-50%,-50%);
          pointer-events:none; animation:spin 30s linear infinite;
        }
        .hero-ring::before {
          content:''; position:absolute; top:-2px; left:50%;
          width:4px; height:4px; border-radius:50%; background:var(--cyan);
          box-shadow:0 0 10px var(--cyan);
        }
        .hero-ring-2 { width:920px; height:920px; animation:spin 50s linear infinite reverse; border-color:rgba(139,92,246,0.04); }
        @keyframes spin { from{transform:translate(-50%,-50%) rotate(0deg)} to{transform:translate(-50%,-50%) rotate(360deg)} }

        .hero-badge {
          display:inline-flex; align-items:center; gap:8px; padding:9px 20px;
          border:1px solid rgba(198,241,53,0.25); border-radius:999px;
          background:rgba(198,241,53,0.06); font-size:11px; font-weight:700;
          letter-spacing:2.2px; text-transform:uppercase; color:var(--lime);
          margin-bottom:36px; animation:riseIn 0.9s cubic-bezier(0.16,1,0.3,1) 0.18s both;
        }
        .badge-pulse { width:7px; height:7px; border-radius:50%; background:var(--lime); animation:badgePulse 2s ease infinite; }
        @keyframes badgePulse { 0%,100%{box-shadow:0 0 0 0 rgba(198,241,53,0.48)} 50%{box-shadow:0 0 0 6px rgba(198,241,53,0)} }

        .hero-h1 {
          font-family:var(--font-display); font-size:clamp(60px,9vw,118px);
          font-weight:900; line-height:0.91; letter-spacing:-4px;
          max-width:1120px; margin-bottom:28px;
          animation:riseIn 0.9s cubic-bezier(0.16,1,0.3,1) 0.34s both;
        }
        .h1-white { display:block; color:var(--text); }
        .h1-lime  { display:block; color:var(--lime); text-shadow:0 0 84px rgba(198,241,53,0.18); }
        .h1-ghost { display:block; color:transparent; -webkit-text-stroke:1px rgba(226,236,255,0.12); }

        .hero-p {
          font-size:18px; font-weight:400; color:#8da6c6;
          max-width:700px; line-height:1.9; margin-bottom:42px;
          animation:riseIn 0.9s cubic-bezier(0.16,1,0.3,1) 0.5s both;
        }

        .hero-actions {
          display:flex; gap:14px; align-items:center; flex-wrap:wrap;
          justify-content:center; margin-bottom:78px;
          animation:riseIn 0.9s cubic-bezier(0.16,1,0.3,1) 0.66s both;
        }
        .btn-lime,.btn-outline {
          display:inline-flex; align-items:center; gap:10px;
          padding:17px 36px; font-size:15px; border-radius:15px;
          text-decoration:none; transition:all 0.3s cubic-bezier(0.34,1.56,0.64,1);
          font-family:var(--font-display); position:relative; overflow:hidden;
        }
        .btn-lime { background:var(--lime); color:#000; font-weight:800; border:none; box-shadow:0 20px 50px rgba(198,241,53,0.24); }
        .btn-lime::after { content:''; position:absolute; inset:0; background:linear-gradient(135deg,rgba(255,255,255,0.22),transparent); opacity:0; transition:opacity 0.3s ease; }
        .btn-lime:hover { transform:translateY(-3px) scale(1.02); box-shadow:0 20px 54px rgba(198,241,53,0.34),0 0 0 1px rgba(198,241,53,0.35); }
        .btn-lime:hover::after { opacity:1; }
        .btn-outline { color:var(--text); font-weight:700; border:1px solid rgba(226,236,255,0.12); background:rgba(255,255,255,0.03); }
        .btn-outline:hover { border-color:rgba(226,236,255,0.25); background:rgba(226,236,255,0.05); transform:translateY(-1px); }

        .hero-stats {
          display:flex; align-items:stretch;
          border:1px solid var(--line); border-radius:20px; overflow:hidden;
          background:rgba(10,18,32,0.82); backdrop-filter:blur(20px);
          animation:riseIn 0.9s cubic-bezier(0.16,1,0.3,1) 0.82s both;
        }
        .hstat { padding:22px 42px; border-right:1px solid var(--line); text-align:center; }
        .hstat:last-child { border-right:none; }
        .hstat-val {
          font-family:var(--font-display); font-size:31px; font-weight:900; letter-spacing:-1.5px;
          background:linear-gradient(135deg,#fff 40%,rgba(255,255,255,0.48));
          -webkit-background-clip:text; -webkit-text-fill-color:transparent;
          line-height:1; margin-bottom:5px;
        }
        .hstat-lbl { font-size:11px; font-weight:600; color:var(--sub); letter-spacing:0.6px; }

        /* ── MARQUEE ── */
        .marquee-wrap {
          overflow:hidden; border-top:1px solid var(--line); border-bottom:1px solid var(--line);
          padding:18px 0; background:rgba(6,11,18,0.6); position:relative; z-index:1;
        }
        .marquee-track { display:flex; gap:60px; width:max-content; animation:marquee 28s linear infinite; }
        .marquee-item { display:flex; align-items:center; gap:12px; font-size:12px; font-weight:700; letter-spacing:2px; text-transform:uppercase; color:var(--sub); white-space:nowrap; flex-shrink:0; }
        .marquee-dot { width:4px; height:4px; border-radius:50%; background:var(--lime); }
        @keyframes marquee { from{transform:translateX(0)} to{transform:translateX(-50%)} }

        /* ── SECTIONS ── */
        .section { padding:116px 0; position:relative; z-index:1; }
        .wrap { max-width:1280px; margin:0 auto; padding:0 52px; }
        .sec-label { display:inline-flex; align-items:center; gap:8px; font-size:11px; font-weight:700; letter-spacing:2.5px; text-transform:uppercase; color:var(--lime); margin-bottom:18px; }
        .sec-label-line { width:24px; height:1px; background:var(--lime); }
        .sec-header { display:flex; justify-content:space-between; align-items:flex-end; gap:24px; margin-bottom:56px; }
        .sec-h2 { font-family:var(--font-display); font-size:clamp(40px,4.8vw,64px); font-weight:900; letter-spacing:-2.6px; line-height:1.02; margin-bottom:14px; }
        .sec-p { font-size:16px; color:var(--sub); line-height:1.8; max-width:480px; }

        /* ── GRIDS ── */
        .feat-grid    { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; }
        .module-grid  { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; }
        .insight-grid { display:grid; grid-template-columns:1.3fr 1fr 1fr; gap:16px; }
        .journey-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; }

        /* ── CARDS ── */
        .feat-card,.module-card,.insight-card,.journey-card,.cta-wrap {
          background:linear-gradient(180deg,rgba(10,18,32,0.96),rgba(8,14,26,0.98));
          border:1px solid var(--line); border-radius:24px;
          position:relative; overflow:hidden;
          transition:all 0.32s cubic-bezier(0.34,1.56,0.64,1);
        }
        .feat-card::before,.module-card::before,.insight-card::before,.journey-card::before,.cta-wrap::before {
          content:''; position:absolute; left:0; right:0; top:0; height:2px;
          background:linear-gradient(90deg,var(--lime),var(--cyan),var(--violet),var(--amber),var(--rose));
        }
        .feat-card,.module-card,.insight-card,.journey-card { padding:34px 30px; }
        .feat-card:hover,.module-card:hover,.insight-card:hover,.journey-card:hover,.cta-wrap:hover { transform:translateY(-4px); border-color:rgba(198,241,53,0.14); box-shadow:0 20px 60px rgba(0,0,0,0.36); }

        .feat-num { font-family:var(--font-mono); font-size:10px; font-weight:500; color:var(--sub); letter-spacing:1px; margin-bottom:26px; }
        .feat-icon-wrap { width:54px; height:54px; border-radius:14px; display:flex; align-items:center; justify-content:center; font-size:24px; margin-bottom:20px; }
        .feat-title,.module-title,.insight-title,.journey-title { font-family:var(--font-display); font-size:22px; font-weight:800; letter-spacing:-0.7px; margin-bottom:10px; color:var(--text); }
        .feat-desc,.module-desc,.insight-desc,.journey-desc { font-size:14px; color:var(--sub); line-height:1.8; }
        .feat-arrow,.module-arrow { position:absolute; right:28px; bottom:28px; width:38px; height:38px; border-radius:50%; background:rgba(255,255,255,0.04); border:1px solid var(--line); display:flex; align-items:center; justify-content:center; color:var(--sub); font-size:14px; transition:all 0.25s ease; }
        .feat-card:hover .feat-arrow,.module-card:hover .module-arrow { color:var(--lime); border-color:rgba(198,241,53,0.28); }

        .module-card { text-decoration:none; display:block; min-height:232px; }
        .module-top { display:flex; justify-content:space-between; align-items:center; margin-bottom:20px; }
        .module-badge { display:inline-flex; align-items:center; justify-content:center; min-height:28px; padding:0 12px; border-radius:999px; font-size:10px; font-weight:800; letter-spacing:1.3px; text-transform:uppercase; color:var(--text); border:1px solid var(--line); background:rgba(255,255,255,0.04); }
        .module-accent { position:absolute; inset:0 0 auto 0; height:2px; }
        .accent-1{background:linear-gradient(90deg,var(--lime),transparent)}
        .accent-2{background:linear-gradient(90deg,var(--cyan),transparent)}
        .accent-3{background:linear-gradient(90deg,var(--violet),transparent)}
        .accent-4{background:linear-gradient(90deg,var(--amber),transparent)}
        .accent-5{background:linear-gradient(90deg,var(--rose),transparent)}
        .accent-6{background:linear-gradient(90deg,var(--lime),var(--cyan),transparent)}

        .chip { display:inline-flex; align-items:center; gap:6px; padding:5px 14px; border-radius:100px; font-size:10px; font-weight:800; letter-spacing:1.5px; text-transform:uppercase; margin-bottom:20px; }
        .chip-lime   { background:rgba(198,241,53,0.08); color:var(--lime);   border:1px solid rgba(198,241,53,0.2); }
        .chip-cyan   { background:rgba(0,212,255,0.08);  color:var(--cyan);   border:1px solid rgba(0,212,255,0.2); }
        .chip-violet { background:rgba(139,92,246,0.10); color:#b598ff;       border:1px solid rgba(139,92,246,0.24); }

        .terminal { margin-top:24px; background:#040810; border:1px solid rgba(0,212,255,0.1); border-radius:14px; padding:20px 22px; font-family:var(--font-mono); }
        .term-bar { display:flex; gap:6px; margin-bottom:16px; }
        .term-dot { width:10px; height:10px; border-radius:50%; }
        .term-row { display:flex; gap:12px; align-items:baseline; padding:3px 0; }
        .term-key { font-size:10px; font-weight:500; letter-spacing:1px; min-width:56px; color:var(--cyan); }
        .term-val { font-size:12px; color:rgba(226,236,255,0.48); }
        .term-hi  { color:var(--lime); }

        .journey-big { font-family:var(--font-display); font-size:90px; font-weight:900; line-height:0.85; color:transparent; -webkit-text-stroke:1px rgba(198,241,53,0.08); letter-spacing:-6px; margin-bottom:22px; user-select:none; }
        .journey-connector { position:absolute; right:-8px; top:50%; transform:translateY(-50%); width:16px; height:16px; background:var(--void); border:1px solid rgba(198,241,53,0.2); border-radius:50%; display:flex; align-items:center; justify-content:center; font-size:8px; color:var(--lime); }

        .div-line { height:1px; background:linear-gradient(90deg,transparent,var(--line),transparent); margin:0 52px; }

        .cta-wrap { margin:0 52px 110px; border-radius:28px; padding:100px 80px; text-align:center; background:radial-gradient(ellipse 100% 100% at 0% 0%,rgba(198,241,53,0.07) 0%,transparent 50%),radial-gradient(ellipse 80% 80% at 100% 100%,rgba(0,212,255,0.05) 0%,transparent 50%),var(--panel); border:1px solid rgba(198,241,53,0.12); z-index:1; }
        .cta-h2 { font-family:var(--font-display); font-size:clamp(44px,6vw,78px); font-weight:900; letter-spacing:-3px; line-height:0.95; margin-bottom:22px; }
        .cta-sub { font-size:16px; color:var(--sub); line-height:1.8; margin-bottom:40px; }
        .pill-group { display:flex; gap:10px; justify-content:center; flex-wrap:wrap; margin-bottom:34px; }
        .pill { display:inline-flex; align-items:center; gap:6px; padding:8px 16px; border-radius:999px; font-size:13px; font-weight:600; background:rgba(255,255,255,0.04); border:1px solid var(--line); color:var(--sub); }
        .pill-check { color:var(--lime); font-size:12px; }

        .footer { border-top:1px solid var(--line); padding:44px 52px; display:flex; align-items:center; justify-content:space-between; gap:24px; position:relative; z-index:1; flex-wrap:wrap; }
        .footer-links { display:flex; gap:20px; flex-wrap:wrap; }
        .footer-links a { font-size:13px; color:var(--sub); text-decoration:none; transition:color 0.2s; }
        .footer-links a:hover { color:var(--text); }
        .footer-copy { font-size:12px; color:var(--sub); }

        @keyframes riseIn { from{opacity:0;transform:translateY(28px) scale(0.985)} to{opacity:1;transform:translateY(0) scale(1)} }
        ::-webkit-scrollbar{width:5px} ::-webkit-scrollbar-track{background:var(--void)} ::-webkit-scrollbar-thumb{background:rgba(198,241,53,0.15);border-radius:3px}

        @media(max-width:1200px) { .nav-inner{flex-wrap:wrap;padding:10px 0} .nav{height:auto} .nav-center{order:3;width:100%} .hero{min-height:auto;padding-top:130px} .feat-grid,.module-grid,.journey-grid{grid-template-columns:1fr 1fr} .insight-grid{grid-template-columns:1fr} }
        @media(max-width:900px) { .wrap{padding:0 20px} .feat-grid,.module-grid,.journey-grid{grid-template-columns:1fr} .sec-header{flex-direction:column;align-items:flex-start} .hero-stats{flex-direction:column;width:100%;max-width:420px} .hstat{border-right:none;border-bottom:1px solid var(--line)} .hstat:last-child{border-bottom:none} .cta-wrap{margin:0 20px 80px;padding:60px 28px} .footer{padding:36px 20px;flex-direction:column;text-align:center} .div-line{margin:0 20px} .nav-right{width:100%;justify-content:flex-end} }
        @media(max-width:640px) { .hero-h1{letter-spacing:-2px} .hero-p{font-size:16px} .btn-lime,.btn-outline{width:100%;justify-content:center} .hero-actions{width:100%;max-width:380px} .nav-right{flex-wrap:wrap} .btn-nav-ghost,.btn-nav-cta,.btn-nav-danger{flex:1 1 auto} }
      `}</style>

      <div className="page">
        <div className="aurora" style={{ left: mousePos.x, top: mousePos.y }} />

        {/* ════════════════════════════════════════════════
            NAVIGATION — Dietitians added ✅
        ════════════════════════════════════════════════ */}
        <nav className="nav">
          <div className="nav-inner">
            <Link className="logo-mark" href={brandHref}>
              <div className="logo-icon">U</div>
              <span className="logo-text"><em>Urban</em>Well</span>
            </Link>

            <div className="nav-center">
              {NAV_ITEMS.map((item) => (
                <Link
                  key={item.href}
                  className={`nav-pill${item.label === 'Dietitians' ? ' dietitian' : ''}`}
                  href={item.href}
                >
                  {item.label}
                </Link>
              ))}
            </div>

            <div className="nav-right">
              {isLoggedIn ? (
                <>
                  <Link className="btn-nav-ghost" href="/dashboard">Dashboard</Link>
                  <Link className="btn-nav-ghost" href="/profile">Profile</Link>
                  <button className="btn-nav-danger" onClick={handleLogout}>Logout</button>
                </>
              ) : (
                <>
                  <Link className="btn-nav-ghost" href="/login">Log in</Link>
                  <Link className="btn-nav-cta"   href="/signup">Get Started →</Link>
                </>
              )}
            </div>
          </div>
        </nav>

        {/* ════════════════════════════════════════════════
            HERO
        ════════════════════════════════════════════════ */}
        <section className="hero">
          <div className="hero-mesh" />
          <div className="hero-dots" />
          <div className="hero-ring" />
          <div className="hero-ring hero-ring-2" />

          <div className="hero-badge">
            <div className="badge-pulse" />
            Now live — AI Health Platform v2.0
          </div>

          <h1 className="hero-h1">
            <span className="h1-white">Smarter wellness.</span>
            <span className="h1-lime">Real results.</span>
            <span className="h1-ghost">Zero guesswork.</span>
          </h1>

          <p className="hero-p">
            UrbanWell combines AI-generated workouts, expert meal plans, certified trainers, registered dietitians, and real-time progress tracking — all in one premium platform built for people serious about their health.
          </p>

          <div className="hero-actions">
            <Link className="btn-lime" href={isLoggedIn ? '/dashboard' : '/signup'}>
              {isLoggedIn ? 'Go to dashboard' : 'Start for free'}
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
            </Link>
            <Link className="btn-outline" href="/trainers">Explore coaches</Link>
          </div>

          <div className="hero-stats">
            {HERO_STATS.map((s) => (
              <div className="hstat" key={s.label}>
                <div className="hstat-val">{s.value}</div>
                <div className="hstat-lbl">{s.label}</div>
              </div>
            ))}
          </div>
        </section>

        {/* ── MARQUEE ── */}
        <div className="marquee-wrap">
          <div className="marquee-track">
            {[...TRUST_ROW, ...TRUST_ROW].map((t, i) => (
              <div className="marquee-item" key={`${t}-${i}`}>
                <div className="marquee-dot" />{t}
              </div>
            ))}
          </div>
        </div>

        {/* ════════════════════════════════════════════════
            FEATURES
        ════════════════════════════════════════════════ */}
        <section className="section">
          <div className="wrap">
            <div className="sec-header">
              <div>
                <div className="sec-label"><span className="sec-label-line" />Platform</div>
                <h2 className="sec-h2">Everything you need.<br />Properly built.</h2>
              </div>
              <p className="sec-p">Six core capabilities that cover every dimension of your health — from AI-generated training to clinical nutrition and expert bookings.</p>
            </div>
            <div className="feat-grid">
              {FEATURE_CARDS.map((f) => (
                <div className="feat-card" key={f.n}>
                  <div className="feat-num">{f.n} — Feature</div>
                  <div className="feat-icon-wrap" style={{ background: f.bg }}>{f.icon}</div>
                  <div className="feat-title">{f.title}</div>
                  <p className="feat-desc">{f.desc}</p>
                  <div className="feat-arrow">→</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        <div className="div-line" />

        {/* ════════════════════════════════════════════════
            INTELLIGENCE
        ════════════════════════════════════════════════ */}
        <section className="section">
          <div className="wrap">
            <div className="sec-header">
              <div>
                <div className="sec-label"><span className="sec-label-line" />Intelligence</div>
                <h2 className="sec-h2">AI that works with<br />real data.</h2>
              </div>
              <p className="sec-p">From meal generation to workout adaptation — every AI feature is connected to your profile, goals, and progress.</p>
            </div>
            <div className="insight-grid">
              <div className="insight-card">
                <div className="chip chip-lime">AI Core</div>
                <div className="insight-title">Adaptive Wellness Intelligence</div>
                <p className="insight-desc">Your profile powers every recommendation. Goals, activity level, weight, allergies, and logged data feed the AI — creating plans that actually fit your life.</p>
                <div className="terminal">
                  <div className="term-bar">
                    <div className="term-dot" style={{ background:'#ff5f57' }} />
                    <div className="term-dot" style={{ background:'#febc2e' }} />
                    <div className="term-dot" style={{ background:'#28c840' }} />
                  </div>
                  <div className="term-row"><span className="term-key">USER</span><span className="term-val">Majid · Intermediate · <span className="term-hi">Muscle Gain</span></span></div>
                  <div className="term-row"><span className="term-key">PLAN</span><span className="term-val">7-day <span className="term-hi">High Protein</span> · 2800 kcal</span></div>
                  <div className="term-row"><span className="term-key">AI</span><span className="term-val">gpt-4o-mini · <span className="term-hi">response ready</span></span></div>
                  <div className="term-row"><span className="term-key">NEXT</span><span className="term-val"><span className="term-hi">Meals</span> · Workouts · Dietitian booking</span></div>
                </div>
              </div>
              {INSIGHT_CARDS.map((item) => (
                <div className="insight-card" key={item.title}>
                  <div className={`chip ${item.chipClass}`}>{item.chip}</div>
                  <div className="insight-title">{item.title}</div>
                  <p className="insight-desc">{item.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <div className="div-line" />

        {/* ════════════════════════════════════════════════
            MODULES
        ════════════════════════════════════════════════ */}
        <section className="section">
          <div className="wrap">
            <div className="sec-header">
              <div>
                <div className="sec-label"><span className="sec-label-line" />Modules</div>
                <h2 className="sec-h2">Every surface.<br />Fully connected.</h2>
              </div>
              <p className="sec-p">Six core modules that link together — workouts feed progress, meals feed macros, bookings feed your expert network.</p>
            </div>
            <div className="module-grid">
              {MODULE_CARDS.map((m, i) => (
                <Link className="module-card" href={m.href} key={m.title}>
                  <div className={`module-accent ${ACCENT_CLASSES[i % ACCENT_CLASSES.length]}`} />
                  <div className="module-top">
                    <span className="module-badge">{m.badge}</span>
                    <span className="module-arrow">↗</span>
                  </div>
                  <div className="module-title">{m.title}</div>
                  <p className="module-desc">{m.desc}</p>
                </Link>
              ))}
            </div>
          </div>
        </section>

        <div className="div-line" />

        {/* ════════════════════════════════════════════════
            JOURNEY
        ════════════════════════════════════════════════ */}
        <section className="section">
          <div className="wrap">
            <div className="sec-header">
              <div>
                <div className="sec-label"><span className="sec-label-line" />Journey</div>
                <h2 className="sec-h2">From first visit to<br />real progress.</h2>
              </div>
              <p className="sec-p">Three clear stages. Every feature is designed to move you forward — not just track data, but change behaviour.</p>
            </div>
            <div className="journey-grid">
              {JOURNEY_STEPS.map((s, i) => (
                <div className="journey-card" key={s.n}>
                  <div className="journey-big">{s.n}</div>
                  <div className="journey-title">{s.title}</div>
                  <p className="journey-desc">{s.desc}</p>
                  {i < JOURNEY_STEPS.length - 1 && <div className="journey-connector">›</div>}
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ════════════════════════════════════════════════
            CTA
        ════════════════════════════════════════════════ */}
        <div className="cta-wrap">
          <h2 className="cta-h2">
            Your health.<br />
            <span style={{ color:'var(--lime)' }}>Finally in one place.</span>
          </h2>
          <p className="cta-sub">Join 47,000+ people using UrbanWell to train smarter, eat better, and stay consistent — with real AI, real experts, and real results.</p>
          <div className="pill-group">
            {['AI Workout Engine','Expert Meal Plans','Certified Trainers','Registered Dietitians','Progress Tracking','Supplement Store'].map((p) => (
              <div className="pill" key={p}><span className="pill-check">✓</span>{p}</div>
            ))}
          </div>
          <Link className="btn-lime" href={isLoggedIn ? '/dashboard' : '/signup'} style={{ display:'inline-flex' }}>
            {isLoggedIn ? 'Continue to dashboard' : 'Create free account'}
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
          </Link>
        </div>

        {/* ── FOOTER ── */}
        <footer className="footer">
          <Link className="logo-mark" href={brandHref}>
            <div className="logo-icon">U</div>
            <span className="logo-text"><em>Urban</em>Well</span>
          </Link>
          <p className="footer-copy">© 2026 UrbanWell. All rights reserved.</p>
          <div className="footer-links">
            {NAV_ITEMS.map((item) => (
              <Link key={item.href} href={item.href}>{item.label}</Link>
            ))}
          </div>
        </footer>
      </div>
    </>
  );
}